#!/bin/sh
set -e


# TODO: Add support for host-specific package installation
# TODO: Define packagelists in separate file(s)
# TODO: Install reniced, configure

if [ ! -f "/etc/apt/apt.conf.d/99no-recommends" ]
then
echo "I: Configuring no-recommends..."
cat > /etc/apt/apt.conf.d/99no-recommends << \EOF
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF
fi

echo "I: Configuring GRUB timeout..."
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=1/g' /etc/default/grub
update-grub

echo "I: Configuring APT components..."
sed -i 's/main$/main contrib non-free/g' /etc/apt/sources.list

apt-get update
export DEBIAN_FRONTEND="noninteractive"

echo "I: Installing essential packages..."
apt-get -y install git etckeeper
apt-get -y install vim vim-scripts
apt-get -y install build-essential packaging-dev


apt-get -y install task-xfce-desktop kupfer chromium terminator xfce4-goodies xfce4-notifyd
apt-get -y install openssh-server

echo "I: Configure openssh-server..."
adduser --system sshusers
sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
grep -q '^AllowGroups sshusers' /etc/ssh/sshd_config || echo 'AllowGroups sshusers' >>/etc/ssh/sshd_config
service ssh restart

apt-get -y install ufw
ufw allow 22/tcp
ufw enable

apt-get -y install pcscd opensc
apt-get -y install vagrant virtualbox
apt-get -y install fonts-lato fonts-inconsolata
apt-get -y install xdg-utils xdg-user-dirs xdg-user-dirs-gtk
apt-get -y install xtrlock
apt-get -y install htop screen
apt-get -y remove rpcbind

apt-get -y install openvpn
chmod 0700 /etc/openvpn
adduser --system --no-create-home --home /dev/null --shell /bin/false --gecos "OpenVPN" --group openvpn


apt-get -y install libreoffice libreoffice-voikko libreoffice-gtk
apt-get -y install apparmor apparmor-docs apparmor-easyprof apparmor-notify apparmor-profiles apparmor-utils
apt-get -y install lm-sensors cpufreqd cpufrequtils

apt-get -y install parted gparted

apt-get -y autoremove
